FROM ubuntu

MAINTAINER Isaac Chang <dimang777@gmail.com>

RUN apt-get update -y && \
    apt-get install -y python3-pip python3-dev

COPY ./WineTales-docker-ubuntu-local/requirements.txt /requirements.txt
COPY ./Dockerfile_WineTales-ubuntu-local /Dockerfile

WORKDIR /

RUN pip3 install -r requirements.txt

COPY ./WineTalesApp /WineTalesApp

WORKDIR /WineTalesApp

ENTRYPOINT [ "python3" ]

CMD [ "server.py" ]


