FROM alpine

MAINTAINER Isaac Chang <dimang777@gmail.com>

RUN apk --no-cache update
RUN apk --no-cache add py-pip python3-dev
RUN apk --no-cache add musl-dev linux-headers g++

COPY ./WineTales-docker-local/requirements.txt /requirements.txt
COPY ./Dockerfile_WineTales-docker-local /Dockerfile

WORKDIR /

RUN pip3 install -r requirements.txt

COPY ./WineTalesApp /WineTalesApp

WORKDIR /WineTalesApp

ENTRYPOINT [ "python3" ]

CMD [ "server.py" ]


