# getting base image - linux
FROM alpine

MAINTAINER Isaac Chang <dimang777@gmail.com>

# executed when building image
# RUN apt-get update

# executed when only creating container from image
# CMD ["echo", "Hello World...! from my first docker image"]
COPY script.sh /script.sh
CMD ["/script.sh"]


